version: '3.8'

services:
  web:
    image: harbor.cu.ac.kr/mwn/backend:latest
    container_name: mwn_backend
    ports:
      - "5000:5000"
    volumes:
      # Mount instance directory to persist SQLite database
      - ./instance:/app/instance
      # Mount logs
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python app.py
