apiVersion: apps/v1
kind: Deployment
metadata:
  name: mwn-backend
  namespace: mwn
  labels:
    app: mwn-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mwn-backend
  template:
    metadata:
      labels:
        app: mwn-backend
    spec:
      containers:
      - name: mwn-backend
        image: harbor.cu.ac.kr/mwn/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: mwn-secret
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        - name: instance-volume
          mountPath: /app/instance
      volumes:
      - name: log-volume
        emptyDir: {}
      - name: instance-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mwn-backend-service
  namespace: mwn
spec:
  type: LoadBalancer
  selector:
    app: mwn-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
